image: docker:stable

services:
  - docker:18.09.7-dind

variables:
  DOCKER_HOST: tcp://localhost:2375

cache:
  paths:
    - .dockerfile_shas

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_TOKEN"

build:
  script:
    - ./bin/build.sh
  only:
    refs:
      - master
  except:
    changes:
      - README.md
      - .gitignore